# Generated by Django 5.1.2 on 2024-11-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("reservation", "New Reservation"),
                    ("message", "New Message"),
                    ("like", "New Like"),
                    ("status_update", "Status Update"),
                ],
                max_length=20,
            ),
        ),
    ]
