# Generated by Django 5.1.2 on 2024-11-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="report_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
