# Generated by Django 5.1.2 on 2024-11-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_reservation_report_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
