# Generated by Django 5.1.2 on 2024-11-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coins",
            field=models.IntegerField(default=0),
        ),
    ]
