# Generated by Django 5.1.2 on 2024-11-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_coins"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coins_bought",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="coins_spent",
            field=models.IntegerField(default=0),
        ),
    ]
