# Generated by Django 5.1.2 on 2024-11-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_post_likes_count_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="initial_quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
