# Generated by Django 5.1.2 on 2024-11-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_post_initial_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
